version: '3.7'
services:
  react_app:
    image: crajaganesh/databui:v1
    restart: always
    ports:
      - "80:80"
    depends_on:
      - hasura
      - express_server
    healthcheck:
      test: ["CMD", "wget", "http://localhost"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - datab

  express_server:
    image: crajaganesh/databsvr:v1
    restart: always
    environment:
      - PORT=8082
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - datab

  hasura:
    image: hasura/graphql-engine:v2.33.0.cli-migrations-v3
    volumes:
      - ./backend/hasura/migrations:/hasura-migrations
      - ./backend/hasura/metadata:/hasura-metadata
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: "${HASURA_GRAPHQL_METADATA_DATABASE_URL}"
      PG_DATABASE_URL: "${PG_DATABASE_URL}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 120
    restart: always
    networks:
      - datab
    depends_on:
      express_server:
        condition: service_healthy

volumes:
  db_data:
      name: db_data

networks:
  datab:
    driver: bridge
    name: datab
